GEON-PPANG/GEON-PPANG-SERVER

api/src/main/java/com/org/gunbbang/controller/BakeryController.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDto.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/MenuResponseDto.java
api/src/main/java/com/org/gunbbang/service/BakeryService.java
common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryCategoryRepository.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
storage/db-core/src/main/java/com/org/gunbbang/repository/MenuRepository.java
storage/db-core/src/main/resources/init/h2-data.sql

- feat/#17 -> dev
- path variable을 통해 특정 건빵집의 상세 정보를 조회할 수 있는 api를 개발했습니다
- 유저의 액세스 토큰이 유효하지 않으면 404 forbidden 에러가 발생하는데 이거는 어디에서 커스텀 에러처리를 해줄 수 있는지 궁금합니다!

[FEAT] 건빵집 상세정보 조회 구현해라

---

api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDto.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseBakeryListResponseDTO.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseBakeryResponseDTO.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/BestBakeryListResponseDTO.java

- fix/#36 -> dev
- closed #36
- BakeryDetailResponseDto가 BaseBakeryResponseDto를 상송받도록 수정했습니다
- baseDto를 추출해준 승하언냐 진짜 고맙습니다링!!

[FIX] BakeryDetailResponseDto를 BaseBakeryResponseDto를 상속받는 클래스로 수정해라

---

api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
api/src/main/java/com/org/gunbbang/controller/BakeryController.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListResponseDto.java

- feat/#38 -> dev
- closed #38
- BakeryListResponseDto가 BaseBakeryResponseDto를 상속받도록 수정했습니다
- X

[FIX] BakeryListResponseDto를 BaseBakeryResponseDto를 상속받는 클래스로 수정해라

---

api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListReviewedByMemberDto.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseBakeryResponseDTO.java
api/src/main/java/com/org/gunbbang/controller/MemberController.java
api/src/main/java/com/org/gunbbang/service/ReviewService.java
common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java

- feat/#25 -> dev
- closed #25
- 회원이 남긴 리뷰를 빵집 정보에 기반해 리스트 형태로 데이터를 받을 수 있는 api를 개발했습니다
- 현재 연결된 h2 데이터베이스에 빵집이 하나 뿐이라 리뷰가 모두 같은 빵집에 대해 작성 및 조회되고 있습니다 
- 리뷰는 최근에 등록된 순으로 정렬했습니다

[FEAT] 회원이 남긴 리뷰를 빵집 정보에 기반해 리스트 형태로 데이터를 받을 수 있는 기능을 구현해라

---

api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseReviewResponseDto.java
api/src/main/java/com/org/gunbbang/controller/DTO/response/ReviewDetailResponseDto.java
api/src/main/java/com/org/gunbbang/controller/ReviewController.java
api/src/main/java/com/org/gunbbang/service/ReviewService.java
common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java

- feat/#26 -> dev
- closed #26
- 유저가 작성한 리뷰를 모아볼 때, 리뷰를 남긴 건빵집을 선택하면 리뷰 상세보기 페이지로 이동하는데, 이 때 필요한 정보를 전달하는 기능을 구현했습니다
- review도 baseDto를 생성해보았는데 확인 부탁드립니다!

[FEAT] 리뷰 상세보기(리뷰 모아보기 상세) 기능 구현해라

---

api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java
api/src/main/java/com/org/gunbbang/login/CustomUserDetails.java
api/src/main/java/com/org/gunbbang/login/service/CustomLoginService.java
api/src/main/java/com/org/gunbbang/util/Security/SecurityUtil.java

feature/#49 -> dev
커스텀한 UserDetails에서 회원의 빵유형 / 주목적 / 영양성분 공개 정보를 가져오도록 수정하였습니다

[FEAT] CustomUserDetails에서 현재 접속한 회원의 빵유형, 주목적, 영양성분 공개 정보를 가져와라

---

api/src/main/java/com/org/gunbbang/controller/DTO/request/ValidateEmailRequestDTO.java
api/src/main/java/com/org/gunbbang/controller/ValidationController.java
api/src/main/java/com/org/gunbbang/service/MemberService.java

feature/#52 -> dev
- 이메일 중복체크 api 추가
- 이메일 및 닉네임 입력 시 앞뒤 공백 체거
- 회원가입 시 앞뒤 공백 체거

[FEAT] 이메일 중복체크 기능 추가 및 닉네임 중복체크 버그 해결

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
storage/db-core/src/main/resources/init/h2-data.sql

feature/#60 -> dev
베스트 건빵집 조회 시
1. 베스트 건빵집 기준으로 조회하고
2. 현재 접속 중인 유저가 선택한 빵유형을 판매하는 건빵집 조회했을 때도
10개가 채워지지 않은 경우 랜덤 건빵집 채워서 10개로 보내주는 기능 구현

[FEAT] 베스트 건빵집 조회 시 10개 모자랐을 때 랜덤으로 추가로 조회

---

api/src/main/java/com/org/gunbbang/service/ReviewService.java
storage/db-core/src/main/resources/init/h2-data.sql

feature/#63 -> dev
홈에서 베스트 리뷰 조회 시 리뷰 키워드가 1개밖에 없을 때 다른 한 값은 null로 응답하도록 수정

[FIX] 리뷰 키워드 1개밖에 없을 때 다른 한 값은 null로 응답해라

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java

- fix/#67 -> dev
- closed #67 
- 빵집 리스트에서 bookmark 여부에 대한 정보가 필요한 경우에 대한 로직을 합칠 수 있는 함수를 적용했습니다

[FIX] 건빵집 bakery service 로직에서 bookMark 판별 로직을 분리해라

---

api/src/main/java/com/org/gunbbang/controller/ReviewController.java
common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java

- feat/#77 -> dev
- closed #77
- 리뷰 좋아요 선택시 리뷰키워드를 선택하지 않아도 저장되는 로직을 수정

[FIX] 리뷰 좋아요 선택시 리뷰키워드를 선택하지 않아도 저장되는 로직을 수정해라

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java

fix/#87 -> dev
베스트 베이커리 조회 시 무조건 10개 내려오도록 alreadyFoundBakeries에 Long 최대값 추가

[FIX] 베스트 베이커리 조회 시 무조건 10개 내려오도록 버그 수정하라

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java

fix/#87 -> dev
베스트 베이커리 조회 시 빈 배열만 나가는 에러를 또ㅋㅋ 해결하라

[FIX] 베스트 베이커리 조회 시 빈 배열만 나가는 에러를 해결하라

---

api/src/main/java/com/org/gunbbang/service/ReviewService.java

bug/#113 -> dev
베스트 리뷰 조회 시 빈 배열로 나가는 에러 수정하라

[BUG] 베스트 리뷰 조회 시 빈 배열로 나가는 에러 수정하라

---

api/src/main/java/com/org/gunbbang/controller/BookMarkController.java
api/src/main/java/com/org/gunbbang/controller/SearchController.java
api/src/main/java/com/org/gunbbang/service/BookMarkService.java
api/src/main/java/com/org/gunbbang/util/mapper/BookMarkMapper.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BookMarkRepository.java

refactor/#125 -> dev
- 하나 큰 메서드를 여러 작은 메서드로 구분
함수 구분 기준이 감이 잘 안잡혀서 리뷰 볼 때 BookMarkService 클래스 위주로 봐주시면 감사하겠습니다

[FIX] 북마크하는 api 를 리팩토링하라

---

api/src/main/java/com/org/gunbbang/controller/SearchController.java
api/src/main/java/com/org/gunbbang/service/BakeryService.java
api/src/main/java/com/org/gunbbang/service/specification/BakerySpecifications.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java

- feature/#138 -> dev
- closed #138
- 빵집 이름으로만 검색 가능했던 기능에 지역명과 가까운 역명으로 검색해도 찾을 수 있도록 기능을 추가했습니다
- 작성해주신 매퍼 잘 사용했습니다
- Specification으로 가져온 값들을 and 조건으로 엮어 다중 키워드 검색 시 모두 포함되는 결과만 반환하도록 노력했습니다
- 예를 들어 서울 강남이라고 검색하면 서울 or 강남이 아닌 서울 and 강남인 빵집이 나오도록 했습니다

[FEAT] 빵집 이름 검색에 근처 역명/지역명으로 검색해도 해당되는 빵집을 찾을 수 있도록 기능 추가해라

---

api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDTO.java
api/src/main/java/com/org/gunbbang/service/BakeryService.java
api/src/main/java/com/org/gunbbang/util/ConstantVO.java
api/src/main/java/com/org/gunbbang/util/mapper/BakeryMapper.java
api/src/main/java/com/org/gunbbang/util/mapper/MenuMapper.java

- fix/#143 -> dev
- closed #143
- Mapper를 이용하여 리팩토링 실시했습니다
- 빵집 상세보기 ResponseDTO에서 운영시간에 대한 필드 이름이 엔티티와 다른 것을 확인하고 엔티티에 맞춰 "openingHours"로 변경했습니다
- 단순 매개변수 전달을 위한 변수 선언에 대해 어떻게 생각하시는지 궁금합니다!

[FIX] 빵집 상세보기 리팩터링

---

api/src/main/java/com/org/gunbbang/controller/ReviewsController.java
api/src/main/java/com/org/gunbbang/service/BakeryService.java
api/src/main/java/com/org/gunbbang/service/ReviewService.java
api/src/main/java/com/org/gunbbang/util/ConstantVO.java
storage/db-core/src/main/resources/init/h2-data.sql

- fix/#147 -> dev
- closed #147
- 리뷰키워드 등록은 좋아요인 리뷰에만 동작하는 기능이기 때문에 service단에서 처리하도록 로직을 수정해보았습니다!
- 리뷰 등록하기 API는 h2 데이터베이스에서는 리뷰 더미가 있을 경우에 제대로 동작하지 않는 것 같습니다.. 혹시라도 테스트 해보신다면 init sql에서 리뷰랑 리뷰키워드 더미는 제외하고 테스트하셔야 할 것 같습니다! 이건 앱잼때도 그랬는데 RDS에서는 발생하지 않았던 오류에요 ㅎㅎ

[FIX] 리뷰 작성하기 API 내에서 리뷰키워드 등록하는 로직 service 단에서 해결해라

---

api/src/main/java/com/org/gunbbang/service/MemberService.java
api/src/main/java/com/org/gunbbang/util/mapper/MemberTypeMapper.java

- fix/#151 -> dev
- closed #151
- 마이페이지에서 필요한 회원 정보를 가져올 때 securityUtil을 사용하도록 코드를 수정했습니다
- Mapper 사용하여 리팩토링 진행했습니다
- 지금 멤버와 관련되서 사용되는 Mapper이름이 MemberType Mapper인데 여기 안에 memberdetailDTO 반환하는 코드도 추가해서 MemberMapper로 이름 변경하는건 어떠신지 궁금합니다! 괜찮다고하시면 제가 적용하고 push할게요 ^0^

[FIX] 마이페이지 조회 API 회원 정보 가져오는 로직 수정 및 리팩터링해라

---

api/src/main/java/com/org/gunbbang/service/MemberService.java
api/src/main/java/com/org/gunbbang/service/ReviewService.java
api/src/main/java/com/org/gunbbang/util/mapper/RecommendKeywordMapper.java
api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java

- fix/#153 -> dev
- closed #153
- 리뷰 상세조회 시 추천 키워드를 가져오는 로직을 이전에 함수로 분리했어서 그 함수를 사용하도록 수정했습니다
- 리턴 값은 ReviewMapper를 사용하여 반환하도록 수정했습니다

[FIX] ReviewService에서 리뷰 상세조회 시 추천 키워드 가져오는 로직은 함수를 사용하고 리턴 값에 Mapper 적용해라

---

api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
api/src/main/java/com/org/gunbbang/service/BakeryService.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryCategoryRepository.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
storage/db-core/src/main/resources/init/h2-data.sql

- closed #159
- 건빵집 리스트에 사용자 맞춤 필터 적용하기 기능 추가
- QueryParameter 변수명 수정
- 우선 순위 적용
- 유저가 선택한 카테고리가 2개 이상일 때 2개 -> 1개 일치하는 순으로 빵집 정렬
- 유저가 맞춤 필터를 선택한 경우 -> 하나라도 일치하는 빵집이면 노출
- 유저 필터 적용 + 카테고리 선택 시 리뷰 많은순으로 정렬되면 리뷰 많은 순이 가장 많은 가중치를 얻어 정렬됨
- feat/#159라고 해야하는데 요즘 리팩토링 많이하다보니 습관적으로 fix라고 붙였네요 죄송합니다..ㅎ

[FEAT] 건빵집 리스트 조회 API 수정사항 반영하여 추가 기능 구현해라

---

api/src/main/java/com/org/gunbbang/jwt/filter/JwtExceptionFilter.java
api/src/main/java/com/org/gunbbang/service/BakeryService.java
api/src/main/java/com/org/gunbbang/service/ReviewService.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java

fix/#168 -> dev
- 회원이 필터칩 선택을 안했을 시 홈에서 베스트 리뷰와 랜덤 베스트 건빵집 반환
이슈가있읍니다,,,, 베스트 리뷰 조회 시 SELECT문에 DTO가 들어가서 그런지 `ORDER BY RAND()` 문에서 `Order by expression "RAND()" must be in the result list in this case;` 에러가 발생합니다,,, native query를 쓰는 수밖에 없을 것 같은데 현업에서는 쓰지 않는다고 들어서요 혹시 해결책은 없을지,,, 아신다면 공유 부탁드립니다,,,,,

[FIX] 베스트 컨텐츠 조회 api 수정

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java

- fix/#174 -> dev
- closed #174
- Comparator에서 long으로 인식하여 내림차순 정렬되도록 수정했습니다

[FIX] 건빵집 리스트 조회에서 정렬 조건 제대로 인식되지 않는 문제 해결해라

---

api/src/main/java/com/org/gunbbang/service/AppleAuthService.java
api/src/main/java/com/org/gunbbang/service/NativeAuthService.java
common/exception/src/main/java/com/org/gunbbang/BadRequestException.java

fix/#177-1 -> dev
- 애플로그인 시 request body에서 email 필드를 가져오도록 수정
- 자체로그인 null 체크 추가

[FIX] 애플로그인 시 request body에서 email 필드를 가져오도록 수정

---

api/src/main/java/com/org/gunbbang/controller/ReviewsController.java
api/src/main/java/com/org/gunbbang/service/ReviewService.java
common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java

- fix/#193 -> dev
- closed #193
- 별로에요 리뷰에서 추천 키워드가 입력되면 에러를 반환하도록 로직을 수정했습니다
- 입력값 검증을 contoller 단에서 하는게 좋을지, 아니면 service 단에서 하는게 좋을지 궁금합니다!

[FIX] 별로에요인 리뷰에서 추천키워드가 함께 입력되면 에러를 반환해라

---

api/src/main/java/com/org/gunbbang/service/ReviewService.java

- fix/#196 -> dev
- closed #196
- 맛있어요와 특별해요 키워드에 대한 퍼센트가 같게 전달되는 문제를 해결했습니다

[FIX] 키워드 퍼센트 반환 시 특별해요 퍼센트 계산 인자를 수정해라

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java
common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BreadTypeRepository.java

- feat/#198 -> dev
- closed #198
- 건빵집 리스트 조회 시, 필터 선택을 하지 않은 유저가 personalFilter를 true로 요청 보낼 시에 대한 에러 처리를 추가했습니다

[FIX] 빵유형을 선택하지 않은 유저가 pesonalFilter true로 요청할 시에 대한 에러처리를 추가해라

---

api/src/main/java/com/org/gunbbang/service/ReviewService.java

- fix/#200 -> dev
- closed #200
- 좋아요 리뷰 작성 시 추천 키워드를 한개 이상 선택하지 않으면 에러를 반환합니다

[FIX] 좋아요 리뷰 작성 시 추천키워드 한개 이상 선택하지 않으면 에러를 반환해라

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
storage/db-core/src/main/java/com/org/gunbbang/repository/MemberNutrientTypeRepository.java

- feat/#267 -> dev
- closed #267 
- 건빵집 리스트 기획 요구사항 반영
- 더미데이터의 건빵집이 너무 많아 모든 빵집을 불러와 List에 저장하여 각 일치 개수를 세는 것이라고 생각해 성아언니와 이야기하여 2릴 때 페이지네이션을 도입하여 수정하기로했습니다
- 현재 로직은 카테고리에서 1개 이상 일치 and 빵 유형에서 1개 이상 일치 and 사용자의 영양성분공개 정도와 일치
- 위에 작성한 세가지 조건을 모두 만족해야지만 건빵집이 출력되는 상태입니다
- 기획 더미데이터 마감 후 local에서 50개 이상의 빵집을 넣고 테스트 한번 해봐야할 것 같습니다
- 중요
- INGREDIENT_OPEN 인 경우 다대다 테이블에 NUTRIENT_OPEN, NOT_OPEN 모두 넣어야함 즉, 관계 테이블에 3개의 컬럼을 생성해야 함
- NUTRIENT_OPEN인 경우 NOT_OPEN도 관계 테이블에 추가해야함

[FEAT] 건빵집 리스트 조회 테이블 변경에 따른 수정

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java

- feat/#286 -> dev
- closed #286
- 필터칩을 설정하지 않은 유저가 건빵집 리스트 조회에서 개인 맞춤형 필터를 설정하려고 할 경우에 대해 예외처리를 추가했습니다
- 전반적인 리팩토링이 필요해 보입니다 하하..

[FEAT] 필터칩을 선택하지 않은 유저가 건빵집 리스트에서 개인 맞춤 필터를 사용하려고 하는 경우에 대한 예외 처리 구현

---

storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java

- fix/#294 -> dev
- closed #294
- 기획 요구사항에 맞추어 빵 타입 유형이 일치하는 것 이후에 리스트 뷰의 카테고리를 반영합니다
- LEFT 조인에서 inner 조인으로 변경하였습니다

[FIX] 건빵집 리스트에서 사용되는 쿼리에서 left 조인을 inner 조인으로 변경

---

api/src/main/java/com/org/gunbbang/service/BakeryService.java
api/src/main/java/com/org/gunbbang/service/ReviewService.java
storage/db-core/src/main/java/com/org/gunbbang/entity/BakeryBreadType.java
storage/db-core/src/main/java/com/org/gunbbang/entity/BakeryNutrientType.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
storage/db-core/src/main/java/com/org/gunbbang/repository/BookMarkRepository.java
storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java

dev -> prod
- QA 시 베스트 리뷰 조회 시 조건에 맞는 회원이 리뷰를 작성해도 다른 회원의 홈화면에 베스트 리뷰로 뜨지 않는 이슈 발생
- 베스트 리뷰 및 베스트 건빵집 조회 시 조회하려는 회원의 필터가 선택되어 있는지 확인하는 isFilterSelected 메서드를 잘못 구현해서 수정한 뒤 이슈 해결했습니다

베스트 빵집 및 베스트 리뷰 조회 시 버그 발생 해결
