GEON-PPANG/GEON-PPANG-SERVER

storage/db-core/src/main/java/com/org/gunbbang/entity/ReviewRecommendKeyword.java, storage/db-core/src/main/resources/init/h2-schema.sql
=> [CHORE] 리뷰-리뷰키워드 테이블 간 잘못 매핑되어 있는 부분을 해결하라

api/build.gradle, api/src/main/java/com/org/gunbbang/controller/BookMarkController.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/BookMarkRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/BookMarkResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/VO/CurrentMemberVO.java, api/src/main/java/com/org/gunbbang/service/BookMarkService.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, common/exception/src/main/java/com/org/gunbbang/DoubleBookMarkRequestException.java, common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java, storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java, storage/db-core/src/main/java/com/org/gunbbang/entity/BookMark.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BookmarkRepository.java
feature/#23 -> dev
북마크 기능을 추가했습니다
=> [FEAT] 북마크 기능 추가

api/src/main/java/com/org/gunbbang/controller/DTO/request/MemberTypesRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberTypesResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/NutrientTypeResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/MemberController.java, api/src/main/java/com/org/gunbbang/controller/SearchController.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java, storage/db-core/src/main/java/com/org/gunbbang/entity/Member.java, storage/db-core/src/main/java/com/org/gunbbang/repository/MemberRepository.java
feature/#31 -> dev
유저 필터칩 변경하는 api를 개발했습니다
=> [FEAT] 유저 필터칩 변경 기능을 구현하라

api/src/main/java/com/org/gunbbang/controller/MemberController.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
feature/#33 -> dev
회원 필터칩 조회 기능을 구현했습니다
=> [FEAT] 회원 필터칩 조회 기능을 구현하라

api/src/main/java/com/org/gunbbang/controller/BakeriesController.java, api/src/main/java/com/org/gunbbang/controller/BestContentController.java
feature/#20 -> dev
베스트 컨빵집 조회 api를 베스트 컨텐츠 조회 컨트롤러로 분리
=> [CHORE] 베스트 컨빵집 조회 api를 베스트 컨텐츠 조회 컨트롤러로 분리하라

api/src/main/java/com/org/gunbbang/controller/BestContentController.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDto.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListResponseDto.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseBakeryResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/BestReviewListResponseDTO.java, api/src/main/java/com/org/gunbbang/service/BakeryService.java, api/src/main/java/com/org/gunbbang/service/BookMarkService.java, api/src/main/java/com/org/gunbbang/service/ReviewService.java, common/domain/src/main/java/com/org/Main.java, common/domain/src/main/java/com/org/gunbbang/BestReviewDTO.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java, storage/db-core/build.gradle, storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java, storage/db-core/src/main/java/com/org/gunbbang/entity/BookMark.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BookMarkRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/RecommendKeywordRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java, storage/db-core/src/main/resources/init/h2-data.sql, storage/db-core/src/main/resources/init/h2-schema.sql
feature/#20 -> dev
베스트 리뷰 조회 기능을 구현함
=> [FEAT] 베스트 리뷰 조회 기능을 개발해라

api/src/main/java/com/org/gunbbang/service/BakeryService.java
feature/#30 -> dev
reviewCount -> resultCoount로 변수명을 변경해라
=> [CHORE] reviewCount -> resultCoount로 변수명을 변경해라

api/src/main/java/com/org/gunbbang/controller/BakeriesController.java, api/src/main/java/com/org/gunbbang/service/BakeryService.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BookMarkRepository.java
feature/#47 -> dev
북마크한 빵집을 조회하는 기능을 추가했습니다
=> [FEAT] 북마크한 빵집 조회 api 추가

api/src/main/java/com/org/gunbbang/config/SecurityConfig.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/ValidateNicknameRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/S3Controller.java, api/src/main/java/com/org/gunbbang/controller/ValidationController.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
feature/#49 -> dev
닉네임 중복 체크 기능을 추가해라
=> [FEAT] 닉네임 중복 체크 기능을 추가해라

api/src/main/java/com/org/gunbbang/controller/SearchController.java
feature/#54 -> dev
건빵집 이름으로 조회 시 앞뒤 공백을 무시하라
=> [FIX] 건빵집 이름으로 조회 시 앞뒤 공백을 무시하라

api/src/main/java/com/org/gunbbang/controller/DTO/response/BookMarkResponseDTO.java, api/src/main/java/com/org/gunbbang/service/BookMarkService.java
feature/#64 -> dev
북마크를 추가하거나 취소할 시 해당 api 응답값에 각각 true/false를 응답하는 flag값을 추가했습니다
=> [FIX] 북마크 추가/취소 flag 변수를 응답에 추가하라

api/src/main/resources/logback-spring.xml, logs/api.log
hotfix/#72 -> dev
로그백 및 applicatiom.yml 파일 수정
=> [FIX] 운영 환경에서의 로그백 파일 에러를 해결하라

api/build.gradle, build.gradle
fix/#80 -> dev
spring-web 의존성을 명시적으로 추가하라
=> [FIX] spring-web 의존성을 명시적으로 추가하라

api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java, common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
fix/#76-2 -> dev 
바인딩 에러에 대해 공통 응답 규격으로 반환하도록 변경하라
=> [FIX] 바인딩 에러에 대해 공통 응답 규격으로 반환하도록 변경하라

api/src/main/java/com/org/gunbbang/controller/DTO/response/BakerySearchResponseDTO.java, api/src/main/java/com/org/gunbbang/service/BakeryService.java, api/src/main/java/com/org/gunbbang/service/BookMarkService.java
fix/#87 -> dev
검색어에 빈 문자열 들어왔을 때 빈 response 반환하는 로직을 추가하라
=> [FIX] 검색어에 빈 문자열 들어왔을 때 빈 response 반환하는 로직을 추가하라

scripts/deploy.sh
fix/#87 -> dev
deploy.sh 파일에 로그 추가하라
=> [FIX] deploy.sh 파일에 로그 추가하라

scripts/deploy.sh
=> [FIX] switch문 로그 추가하라

api/src/main/java/com/org/gunbbang/controller/DTO/response/ReviewCreateResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/ReviewsController.java
=> [FIX] 안드로이드를 위해 리뷰 작성 api의 response data를 null이 아닌 Int으로 반환해라

api/src/main/java/com/org/gunbbang/service/BakeryService.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
fix/#87 -> dev
베스트 건빵집 조회 시 빈 리스트 내려가는 버그를 수정해라
=> [FIX] 베스트 건빵집 조회 시 빈 리스트 내려가는 버그를 수정해라

api/src/main/java/com/org/gunbbang/AOP/ApiInfo/RequestApiInfo.java, api/src/main/java/com/org/gunbbang/AOP/ApiInfo/SearchApiInfo.java, api/src/main/java/com/org/gunbbang/AOP/ApiInfo/SignupApiInfo.java, api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java, api/src/main/java/com/org/gunbbang/AOP/annotation/BakeryIdApiLog.java, api/src/main/java/com/org/gunbbang/AOP/annotation/ReviewIdApiLog.java, api/src/main/java/com/org/gunbbang/AOP/annotation/SearchApiLog.java, api/src/main/java/com/org/gunbbang/AOP/annotation/SignupApiLog.java, api/src/main/java/com/org/gunbbang/AOP/logInfo/BakeryIdLogInfo.java, api/src/main/java/com/org/gunbbang/AOP/logInfo/LogInfo.java, api/src/main/java/com/org/gunbbang/AOP/logInfo/ReviewIdLogInfo.java, api/src/main/java/com/org/gunbbang/AOP/logInfo/SearchLogInfo.java, api/src/main/java/com/org/gunbbang/AOP/logInfo/SignupLogInfo.java, api/src/main/java/com/org/gunbbang/controller/AuthController.java, api/src/main/java/com/org/gunbbang/controller/BakeriesController.java, api/src/main/java/com/org/gunbbang/controller/BookMarkController.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/BookMarkRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/BreadTypeRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/MemberSignUpRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/MemberTypesRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/NutrientTypeRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/RecommendKeywordNameRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/ReviewRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/ValidateEmailRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/ValidateNicknameRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/MemberController.java, api/src/main/java/com/org/gunbbang/controller/ReviewsController.java, api/src/main/java/com/org/gunbbang/controller/SearchController.java, api/src/main/java/com/org/gunbbang/controller/TestController.java
fix/#93 -> dev
api 및 에러 로그 수집을 위해 로깅용 클래스 및 어노테이션을 더 추가했습니다
=> [FIX] api 및 에러 로그 수집을 위한 기능을 더 추가하라

api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java
fix/#93 -> dev
기본 로깅 안되는 버그를 해결하라
=> [FIX] 기본 로깅 안되는 버그를 해결하라

api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java, api/src/main/java/com/org/gunbbang/AOP/logInfo/SignupLogInfo.java
fix/#93 -> dev
회원가입시 주목적도 로그 남도록 수정하라
=> [FIX] 회원가입시 주목적도 로그 남도록 수정하라

api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java, api/src/main/java/com/org/gunbbang/AOP/logInfo/LogInfo.java
fix/#93 -> dev
에러 로그 남길 때 simpleName도 남기도록 수정하라
=> [FIX] 에러 로그 남길 때 simpleName도 남기도록 수정하라

api/build.gradle, api/src/main/java/com/org/gunbbang/GunbbangApplication.java, api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java, api/src/main/java/com/org/gunbbang/support/slack/SlackUtil.java
feature/#118 -> dev
에러 발생 시 슬랙으로 메시지 전송 기능 추가하라
=> [FEAT] 에러 발생 시 슬랙으로 메시지 전송 기능 추가하라

api/src/main/java/com/org/gunbbang/config/SecurityConfig.java, api/src/main/java/com/org/gunbbang/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java, api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java, api/src/main/java/com/org/gunbbang/login/service/CustomUserDetailsService.java, api/src/main/java/com/org/gunbbang/service/MemberService.java
chore/auth -> dev
- CustomLoginService -> CustomUserDetailsService로 이름 변경하라
- 시큐리티 코드에 주석 추가하라
=> [CHORE] CustomLoginService -> CustomUserDetailsService로 이름 변경하라

api/src/main/java/com/org/gunbbang/service/ReviewService.java
=> [BUG] 베스트 리뷰 조회 시 빈 배열로 내려오는 로직 해결 

api/src/main/java/com/org/gunbbang/service/BakeryService.java, api/src/main/java/com/org/gunbbang/service/ReviewService.java
=> [BUG] 베스트 리뷰 조회 api에서 페이지네이션 에러로 500떨어지는 에러 해결하라

api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberTypeResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/MemberController.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, api/src/main/java/com/org/gunbbang/service/ReviewService.java, api/src/main/java/com/org/gunbbang/util/mapper/MemberTypeMapper.java, api/src/main/java/com/org/gunbbang/util/mapper/NutrientTypeMapper.java, common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
- 회원 필터칩 조회 api 리팩토링
- 회원 필터칩 변경 api 리팩토링
- 북마크 모아보기 api 리팩토링
refactor/#126 -> dev
MemberTypeResponseDTO를 빌더를 써서 반환할지 매퍼에서 DTO를 변환해서 반환할지 고민입니다 혹시 의견 있으시면 코멘트 주세요~
=> [FIX] 회원 필터칩 및 북마크 모아보기 관련 api 리팩토링

api/src/main/java/com/org/gunbbang/service/ReviewService.java, api/src/main/java/com/org/gunbbang/util/mapper/BakeryMapper.java, api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java, storage/db-core/src/main/resources/init/h2-data.sql
- fix/#157 -> dev
- closed #157
- Mapper 적용했습니다
- reiview createdAt 필드 Mapping 어노테이션으로 가져오는 방식이 여러개라 통일시켰습니다
=> [FIX] 유저가 작성한 리뷰 빵집 정보를 기반으로 확인하는 API를 리팩터링해라

api/src/main/java/com/org/gunbbang/config/SecurityConfig.java, api/src/main/java/com/org/gunbbang/controller/AuthController.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberWithdrawResponseDTO.java, api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java, lombok.config, storage/db-core/src/main/java/com/org/gunbbang/repository/MemberRepository.java
=> [FEAT] 회원탈퇴 기능 구현(브랜치 삭제 후 다시 pr)

api/src/main/java/com/org/gunbbang/AOP/ApiInfo/RequestApiInfo.java, api/src/main/java/com/org/gunbbang/AOP/ApiInfo/SignupApiInfo.java, api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java, api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java, api/src/main/java/com/org/gunbbang/jwt/filter/JwtExceptionFilter.java, api/src/main/java/com/org/gunbbang/jwt/service/AppleJwtService.java, api/src/main/java/com/org/gunbbang/jwt/service/JwtService.java, api/src/main/java/com/org/gunbbang/login/CustomUserDetails.java, api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java, api/src/main/java/com/org/gunbbang/login/service/CustomUserDetailsService.java, api/src/main/java/com/org/gunbbang/service/BakeryService.java, api/src/main/java/com/org/gunbbang/service/ReviewService.java, api/src/main/java/com/org/gunbbang/support/slack/SlackSender.java, api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java, storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
fix/#177-1 -> dev 
- 필터 선택 안한 회원도 베스트 리뷰 랜덤으로 조회되도록 변경했습니다
- 로컬 테스트 용으로 남긴 로그를 @Slf4j 로 변경하거나 삭제했습니다
=> [FIX] 필터 선택 안한 회원도 베스트 리뷰 렌덤으로 조회되도록 수정하라

api/src/main/java/com/org/gunbbang/controller/AuthController.java, api/src/main/java/com/org/gunbbang/controller/ValidationController.java, storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
fix/#177-1 -> dev
@Valid 어노테이션 추가
=> [CHORE] @Valid 어노테이션 추가

storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
fix/#190 -> dev
리뷰 텍스트가 빈문자열일 경우 베스트 리뷰 조회에서 제외되도록 설정
=> [FIX] 리뷰 텍스트가 빈문자열일 경우 베스트 리뷰 조회에서 제외되도록 설정

api/src/main/java/com/org/gunbbang/controller/DTO/response/ValidationResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/ValidationController.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java, common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
fix/#202 -> dev
이메일 중복체크 및 닉네임 중복체크 성공 시 response body 추가
=> [FIX/#202] 이메일 중복체크 및 닉네임 중복체크 성공 시 response body 추가

api/src/main/java/com/org/gunbbang/login/filter/JsonUsernamePasswordAuthenticationFilter.java, api/src/main/java/com/org/gunbbang/service/AuthService.java, api/src/main/java/com/org/gunbbang/service/AuthServiceProvider.java
소셜로그인 시 자동으로 지정되는 닉네임 이름에서 UUID 제외
=> [FIX] 소셜로그인 시 자동으로 지정되는 닉네임 이름에서 UUID 제외

api/src/main/java/com/org/gunbbang/service/AuthService.java
fix/#202 -> dev
oauth 회원가입에서 @Transactional 어노테이션 추가
=> [FIX] oauth 회원가입에서 @Transactional 어노테이션 추가

api/src/main/java/com/org/gunbbang/service/MemberService.java, api/src/main/resources/logback-spring.xml
=> [CHORE] 로그백 파일 추가

api/src/main/java/com/org/gunbbang/service/MemberService.java
=> [CHORE] 에러 수정

api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java
=> [CHORE] 에러 테스트 api에서 stack trace 출력

api/src/main/java/com/org/gunbbang/AOP/ApiInfo/RequestApiInfo.java, api/src/main/java/com/org/gunbbang/AOP/ApiInfo/SignupApiInfo.java, api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java, api/src/main/java/com/org/gunbbang/config/SecurityConfig.java, api/src/main/java/com/org/gunbbang/controller/ReportController.java, api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java, api/src/main/java/com/org/gunbbang/jwt/filter/JwtExceptionFilter.java, api/src/main/java/com/org/gunbbang/jwt/service/AppleJwtService.java, api/src/main/java/com/org/gunbbang/jwt/service/JwtService.java, api/src/main/java/com/org/gunbbang/login/filter/JsonUsernamePasswordAuthenticationFilter.java, api/src/main/java/com/org/gunbbang/login/handler/CustomLogoutHandler.java, api/src/main/java/com/org/gunbbang/login/handler/LoginFailureHandler.java, api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java, api/src/main/java/com/org/gunbbang/login/handler/LogoutSuccessHandler.java, api/src/main/java/com/org/gunbbang/login/service/CustomUserDetailsService.java, api/src/main/java/com/org/gunbbang/service/AppleAuthService.java, api/src/main/java/com/org/gunbbang/service/BakeryService.java, api/src/main/java/com/org/gunbbang/service/BookMarkService.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, api/src/main/java/com/org/gunbbang/service/NativeAuthService.java, api/src/main/java/com/org/gunbbang/service/ReviewReportService.java, api/src/main/java/com/org/gunbbang/service/ReviewService.java, api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java, api/src/main/java/com/org/gunbbang/support/slack/SlackSender.java, common/domain/src/main/java/com/org/gunbbang/DTO/AppleAuthCodeRequestDTO.java, common/exception/src/main/java/com/org/gunbbang/CustomJwtTokenException.java, common/exception/src/main/java/com/org/gunbbang/NotFoundException.java, common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
=> [FIX] 로그 메시지 및 레벨 리팩토링

api/src/main/java/com/org/gunbbang/service/KakaoAuthService.java
=> [CHORE] 카카오 소셜로그인 디버깅용 코드 추가

api/src/main/java/com/org/gunbbang/auth/jwt/service/AppleJwtService.java, api/src/main/java/com/org/gunbbang/controller/DTO/request/MemberTypesRequestDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/BreadTypeResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberTypeResponseDTO.java, api/src/main/java/com/org/gunbbang/controller/DTO/response/NutrientTypeResponseDTO.java, api/src/main/java/com/org/gunbbang/service/AmplitudeService.java, api/src/main/java/com/org/gunbbang/service/AppleAuthService.java, api/src/main/java/com/org/gunbbang/service/AuthService.java, api/src/main/java/com/org/gunbbang/service/AuthServiceProvider.java, api/src/main/java/com/org/gunbbang/service/KakaoAuthService.java, api/src/main/java/com/org/gunbbang/service/MemberService.java, api/src/main/java/com/org/gunbbang/service/NativeAuthService.java, api/src/main/java/com/org/gunbbang/service/ReviewService.java, api/src/main/java/com/org/gunbbang/service/VO/SignedUpMemberVO.java, api/src/main/java/com/org/gunbbang/util/mapper/BakeryBreadTypeMapper.java, api/src/main/java/com/org/gunbbang/util/mapper/MemberBreadTypeMapper.java, api/src/main/java/com/org/gunbbang/util/mapper/MemberNutrientTypeMapper.java, api/src/main/java/com/org/gunbbang/util/mapper/MemberTypeMapper.java, common/domain/build.gradle, common/domain/src/main/java/com/org/gunbbang/DTO/HttpV2RequestDTO.java, common/domain/src/main/java/com/org/gunbbang/VO/UserPropertyVO.java, storage/db-core/src/main/java/com/org/gunbbang/entity/BreadType.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BreadTypeRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/MemberBreadTypeRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/MemberNutrientTypeRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/NutrientTypeRepository.java, storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
fix/#261 -> dev
- 슬랙으로 요청주신 리뷰 관련 부분 수정했습니다 어차피 안쓰는 메서드라 그냥 삭제했어요
- 회원가입 부분은 논의하고 싶은 부분이 쫌 있어서 그건 차차할게요
- 마찬가지로 성은이가 짠 로직중에 저처럼 안쓰지만 에러나는 메서드가 있던데 일단 주석처리 해서 기동 제대로 되거든요 그거 주석처리 하고 푸시했는데 필요없는 로직이면 삭제해도 괜찮을 것 같습니다
=> [FIX] 기동 시 에러나는 부분 해결

README.md
=> [CHORE] README.md 수정

api/src/main/java/com/org/gunbbang/auth/security/util/SecurityUtil.java, api/src/main/java/com/org/gunbbang/controller/BakeriesController.java, api/src/main/java/com/org/gunbbang/service/BakeryService.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
- feat/#269 -> dev
- 페이지네이션 가능하도록 수정하였습니다
- 토큰없이 API 사용할 수 있도록 수정하였습니다
- 무한 스크롤 관련해서 클라분들께 여쭤보고싶은게 있어서 클라랑 회의 후에 수정 후 머지하도록 하겠습니다!
=> [FEAT] 건빵집 리스트 페이지네이션 가능하도록 수정

api/src/main/java/com/org/gunbbang/service/NativeAuthService.java
fix/#279 -> dev
자체 회원가입 시 응답값 SIGN_UP으로 변경
=> [FIX] 자체 회원가입 시 응답값 SIGN_UP으로 변경

.github/workflows/prod-cd.yml
=> [FIX] 자체 회원가입시 SIGN_UP으로 응답값 변경

api/src/main/java/com/org/gunbbang/service/AmplitudeService.java
fix/#282 -> dev
앰플리튜드 관련 안쓰는 기능 삭제
=> [FIX] 앰플리튜드 관련 안쓰는 기능 삭제

storage/db-core/src/main/java/com/org/gunbbang/entity/BakeryBreadType.java
fix -> #284 
bakeryBreadType 테이블에 bakery_id & bakeryBreadType_id 같이 unique 제약조건 걸었습니다
=> [FIX] bakeryBreadType 테이블에 unique 제약조건 추가

api/src/main/java/com/org/gunbbang/service/BakeryService.java, storage/db-core/src/main/java/com/org/gunbbang/entity/BakeryBreadType.java
=> [MERGE] Prod에 건빵집 리스트 필터칩 적용하지 않은 유저가 API 요청하는 경우에 대한 수정사항 변영

api/src/main/java/com/org/gunbbang/service/BakeryService.java
- fix/#291 -> dev
- closed #291
=> [FIX] 건빵집 리스트에서 회원가입한 유저가 personalFilter를 false로 보내는 경우에 500 에러가 반환되는 이슈 해결

api/src/main/java/com/org/gunbbang/controller/BakeriesController.java, api/src/main/java/com/org/gunbbang/service/BakeryListService.java, api/src/main/java/com/org/gunbbang/service/BakeryService.java, common/enum/src/main/java/com/org/gunbbang/CategoryType.java, storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
=> [HOTFIX] 건빵집 리스트 중복 문제 해결(드디어..)

README.md
=> [MERGE] dev -> prod 머지
